### ISSUE TITLE
Assertion fails with virus="XBB.1.5"

### ISSUE THREAD

**Issue by corneliusroemer** [jbloomlab/SARS2-RBD-escape-calc#3]
When instantiating the calculator with `calc = EscapeCalculator(virus="XBB.1.5")` I get an assertion error for this line in `_init_`:

```py
assert self.sources.issubset(self.data["source"])
```

It seems that the various query/dropping operations above this line have removed a source that is included by default - because that source doesn't have any antibodies that have XBB.1.5 information.

When I run the following for debugging purposes above the failing assertion I get

```py
print(self.sources - set(self.data["source"])) # {'WT vaccinees'}
print(set(self.data["source"]) - self.sources) # {'SARS convalescents'}
```

I think that assertion can just be dropped?

**Comment by jbloom** [comment]
@corneliusroemer I will look in a  few hours at the code bug you mention.

But as a higher-level issue, for your analysis you may be better off using the virus as `XBB` rather than `XBB.1.5`. The reason is that the escape calculator only uses antibodies for which Yunlong Cao's group measured neutralization against the strain of interest. In their (published) datasets, they measured neutralization of substantially more antibodies against `XBB` than `XBB.1.5`, since a lot of their experiments were done before `XBB.1.5` become dominant. You can see this if you look at the antibodies bar chart when toggling `virus against which neutralization measured` between `XBB` and `XB B.1.5` at this [https://jbloomlab.github.io/SARS2-RBD-escape-calc/](https://jbloomlab.github.io/SARS2-RBD-escape-calc/)---there are a lot more antibodies for `XBB`.

Since the antigenic differences between `XBB` and `XBB.1.5` are probably fairly minor (it mostly seems like `XBB.1.5`'s advantage is better transmissibility, possibly in part due to ACE2 affinity), you might be better off using the `XBB`-based escape-calculator values rather than `XBB.1.5`-based ones, even if you are really more interested in `XBB.1.5`-like viruses.

**Comment by jbloom** [comment]
@corneliusroemer, you are 100% correct as far as code bug. I have removed the offending `assert` in #4. Note my comment above though that in practice you may want to use the default of `virus="XBB"` rather than XBB.1.5 due to natural of the underlying experimental data.
